// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBl1wuzqFkILUos3gHHnezxAk_dQE5hxk',
    appId: '1:515864974460:android:9eee6e323409ad6deca5f9',
    messagingSenderId: '515864974460',
    projectId: 'univ-syllabus',
    databaseURL: 'https://univ-syllabus-default-rtdb.firebaseio.com',
    storageBucket: 'univ-syllabus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxHEDzh3NP6uMudZV4KEG2W7cDqAcZWHk',
    appId: '1:515864974460:ios:2281a7c1f07ddf08eca5f9',
    messagingSenderId: '515864974460',
    projectId: 'univ-syllabus',
    databaseURL: 'https://univ-syllabus-default-rtdb.firebaseio.com',
    storageBucket: 'univ-syllabus.appspot.com',
    androidClientId: '515864974460-65v61mkv4lbd92v4dv27e99i0msjfhut.apps.googleusercontent.com',
    iosClientId: '515864974460-i6rftmbi1jkh7lkjll0ok9lipmrqtnnd.apps.googleusercontent.com',
    iosBundleId: 'io.timeschedule.kgu',
  );
}
